apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-frontend
  template:
    metadata:
      labels:
        app: game-frontend
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: html
          configMap:
            name: game-html
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: game-frontend
spec:
  type: NodePort
  selector:
    app: game-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
