apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-backend
  template:
    metadata:
      labels:
        app: game-backend
    spec:
      nodeSelector:
        game-node: "true"
      containers:
      - name: backend
        image: python:3.11-slim
        command: ["python", "-m", "http.server", "5000"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: game-backend
spec:
  selector:
    app: game-backend
  ports:
    - port: 5000
      targetPort: 5000

