- name: Install Calico CNI
  hosts: kube_master
  become: true
  tasks:
    - name: Download and apply Calico manifest
      ansible.builtin.command: >
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
    - name: Install Local Path Provisioner
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
      register: localpath_result
      changed_when: "'created' in localpath_result.stdout or 'configured' in localpath_result.stdout"
      failed_when: localpath_result.rc != 0 and "'AlreadyExists' not in localpath_result.stderr"


