- name: Prepare system
  hosts: kube_all
  become: true
  tasks:
    - name: Disable swap
      ansible.builtin.command: swapoff -a

    - name: Install EPEL repository
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Permanently disable swap
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s)'
        replace: '# \1'

    - name: Load required kernel modules
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Apply sysctl params
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl settings
      ansible.builtin.command: sysctl --system

    - name: Install prerequisites for Docker repo
      ansible.builtin.yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install containerd
      ansible.builtin.yum:
        name: containerd.io
        state: present


    - name: Ensure containerd config directory exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Overwrite containerd config.toml with default config
      ansible.builtin.shell: |
        containerd config default > /etc/containerd/config.toml
      args:
        executable: /bin/bash

    - name: Set SystemdCgroup = true in containerd config
      ansible.builtin.shell: |
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      args:
        executable: /bin/bash

    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true
        daemon_reload: true

 